[server]
maxUploadSize = 4096
enableStaticServing = false
[theme]
primaryColor="#4C7DE7"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#fbfcfc"
textColor="#404040"
[client]
showSidebarNavigation = false
